export const CREATE = 'CREATE';
export const SIGN_UP = 'SIGN_UP';

export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
}

export const categoryConstants = {
    CATEGORY_REQUEST: 'CATEGORY_REQUEST',
    CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
    CATEGORY_FAILURE: 'CATEGORY_FAILURE',
    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
    EDIT_CATEGORY_REQUEST: 'EDIT_CATEGORY_REQUEST',
    EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_FAILURE: 'EDIT_CATEGORY_FAILURE',
    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',
    RESET_RESPONSE: 'RESET_RESPONSE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}

export const productConstants = {
    PRODUCT_REQUEST: 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_FAILURE: 'PRODUCT_FAILURE',
    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
    EXPORT_PRODUCT_STOCKS_REQUEST: 'EXPORT_PRODUCT_STOCKS_REQUEST',
    EXPORT_PRODUCT_STOCKS_SUCCESS: 'EXPORT_PRODUCT_STOCKS_SUCCESS',
    EXPORT_PRODUCT_STOCKS_FAILURE: 'EXPORT_PRODUCT_STOCKS_FAILURE',
    EXPORT_PRODUCTS_REQUEST: 'EXPORT_PRODUCTS_REQUEST',
    EXPORT_PRODUCTS_SUCCESS: 'EXPORT_PRODUCTS_SUCCESS',
    EXPORT_PRODUCTS_FAILURE: 'EXPORT_PRODUCTS_FAILURE',
    DEMO_EXPORT_PRODUCTS_REQUEST: 'DEMO_EXPORT_PRODUCTS_REQUEST',
    DEMO_EXPORT_PRODUCTS_SUCCESS: 'DEMO_EXPORT_PRODUCTS_SUCCESS',
    DEMO_EXPORT_PRODUCTS_FAILURE: 'DEMO_EXPORT_PRODUCTS_FAILURE',
    IMPORT_PRODUCTS_REQUEST: 'IMPORT_PRODUCTS_REQUEST',
    IMPORT_PRODUCTS_SUCCESS: 'IMPORT_PRODUCTS_SUCCESS',
    IMPORT_PRODUCTS_FAILURE: 'IMPORT_PRODUCTS_FAILURE',
    ADD_PRODUCT_STOCK_REQUEST: 'ADD_PRODUCT_STOCK_REQUEST',
    ADD_PRODUCT_STOCK_SUCCESS: 'ADD_PRODUCT_STOCK_SUCCESS',
    ADD_PRODUCT_STOCK_FAILURE: 'ADD_PRODUCT_STOCK_FAILURE',
    RESET_RESPONSE: 'RESET_RESPONSE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}

export const cartConstants = {
    INCREASE: 'INCREASE',
    INCREASE_OPTION: 'INCREASE_OPTION',
    ADD_OPTION: 'ADD_OPTION',
    DECREASE: 'DECREASE',
    DECREASE_OPTION: 'DECREASE_OPTION',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    REMOVE_OPTION_ITEM: 'REMOVE_OPTION_ITEM',
    CLEAR: 'CLEAR',
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE'
}

export const orderConstants = {
    ORDERS_REQUEST: 'ORDERS_REQUEST',
    ORDERS_SUCCESS: 'ORDERS_SUCCESS',
    ORDERS_FAILURE: 'ORDERS_FAILURE',
    EDIT_RESERVED_ORDER_REQEUST: 'EDIT_RESERVED_ORDER_REQEUST',
    EDIT_RESERVED_ORDER_SUCCESS: 'EDIT_RESERVED_ORDER_SUCCESS',
    EDIT_RESERVED_ORDER_FAILURE: 'EDIT_RESERVED_ORDER_FAILURE',
    TEMP_ORDERS_REQUEST: 'TEMP_ORDERS_REQUEST',
    TEMP_ORDERS_SUCCESS: 'TEMP_ORDERS_SUCCESS',
    TEMP_ORDERS_FAILURE: 'TEMP_ORDERS_FAILURE',
    EDIT_TEMP_ORDER_REQEUST: 'EDIT_TEMP_ORDER_REQEUST',
    EDIT_TEMP_ORDER_SUCCESS: 'EDIT_TEMP_ORDER_SUCCESS',
    EDIT_TEMP_ORDER_FAILURE: 'EDIT_TEMP_ORDER_FAILURE',
    DELETE_TEMP_ORDERS_REQUEST: 'DELETE_TEMP_ORDERS_REQUEST',
    DELETE_TEMP_ORDERS_SUCCESS: 'DELETE_TEMP_ORDERS_SUCCESS',
    DELETE_TEMP_ORDERS_FAILURE: 'DELETE_TEMP_ORDERS_FAILURE',
    DELETE_ORDER_REQUEST: 'DELETE_ORDER_REQUEST',
    DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
    DELETE_ORDER_FAILURE: 'DELETE_ORDER_FAILURE',
    CONFIRM_ORDER_REQUEST: 'CONFIRM_ORDER_REQUEST',
    CONFIRM_ORDER_SUCCESS: 'CONFIRM_ORDER_SUCCESS',
    CONFIRM_ORDER_FAILURE: 'CONFIRM_ORDER_FAILURE',
    EXPORT_ORDERS_REQUEST: 'EXPORT_ORDERS_REQUEST',
    EXPORT_ORDERS_SUCCESS: 'EXPORT_ORDERS_SUCCESS',
    EXPORT_ORDERS_FAILURE: 'EXPORT_ORDERS_FAILURE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}

export const userConstants = {
    USER_REQUEST: 'USER_REQUEST',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_FAILURE: 'USER_FAILURE',
    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'ADD_USER_FAILURE',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    RESET_RESPONSE: 'RESET_RESPONSE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}

export const customerConstants = {
    CUSTOMER_REQUEST: 'CUSTOMER_REQUEST',
    CUSTOMER_SUCCESS: 'CUSTOMER_SUCCESS',
    CUSTOMER_FAILURE: 'CUSTOMER_FAILURE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE'
}

export const errorConstants = {
    ERROR_MESSAGE: 'ERROR_MESSAGE',
    ERROR_CLEAR: 'ERROR_CLEAR'
}