export const CREATE = 'CREATE';
export const SIGN_UP = 'SIGN_UP';

export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
}

export const categoryConstants = {
    CATEGORY_REQUEST: 'CATEGORY_REQUEST',
    CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
    CATEGORY_FAILURE: 'CATEGORY_FAILURE',
    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
}

export const productConstants = {
    PRODUCT_REQUEST: 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_FAILURE: 'PRODUCT_FAILURE',
    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE'
}

export const cartConstants = {
    INCREASE: 'INCREASE',
    INCREASE_OPTION: 'INCREASE_OPTION',
    ADD_OPTION: 'ADD_OPTION',
    DECREASE: 'DECREASE',
    DECREASE_OPTION: 'DECREASE_OPTION',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR: 'CLEAR',
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE'
}